// HERO SECTION INFO CONSTANTS
export const HERO_SECTION_WEBSITE_TITLE = "NGT SOFTWARE";
export const HERO_SECTION_WEBSITE_DESQ = "Digital Marketing Agency";
export const HERO_SECTION_WEBSITE_PHN_NO1 = "5656569991";
export const HERO_SECTION_WEBSITE_PHN_NO2 = "5656569992";
export const HERO_SECTION_WEBSITE_EMAIL = "info@software.com";
export const HERO_SECTION_WEBSITE_lOCATION = "location,via";


// HERO SECTION SEO CONSTANTS
export const HERO_SECTION_LOGO_IMAGE_ALT = "NGT-SOFTWARE LOGO";