// HERO SECTION INFO CONSTANTS
export const HERO_SECTION_WEBSITE_TITLE = "NGT SOFTWARE";
export const HERO_SECTION_WEBSITE_DESQ = "Digital Marketing Agency";
// HERO SECTION SEO CONSTANTS
export const HERO_SECTION_LOGO_IMAGE_ALT = "NGT-SOFTWARE LOGO";