// HERO SECTION INFO CONSTANTS
HERO_SECTION_WEBSITE_TITLE = "NGT SOFTWARE";
HERO_SECTION_WEBSITE_DESQ = "Digital Marketing Agency";
HERO_SECTION_WEBSITE_PHN_NO1 = "5656569991";
HERO_SECTION_WEBSITE_PHN_NO2 = "5656569992";
HERO_SECTION_WEBSITE_EMAIL = "info@software.com";
HERO_SECTION_WEBSITE_lOCATION = "location,via";


// HERO SECTION SEO CONSTANTS
HERO_SECTION_LOGO_IMAGE_ALT = "NGT-SOFTWARE LOGO";